package com.axa_space.axa_fmf_closenotification;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PreSubmission_QA_Instructions_Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PreSubmission_QA_Instructions_Object() {
    }




}