package com.axa_space.axa_fmf_closenotification;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TaskNotification implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String taskName;
	private java.lang.Boolean notificationRequired;

	private long processID;

	public TaskNotification() {
	}

	public java.lang.String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(java.lang.String taskName) {
		this.taskName = taskName;
	}

	public java.lang.Boolean getNotificationRequired() {
		return this.notificationRequired;
	}

	public void setNotificationRequired(java.lang.Boolean notificationRequired) {
		this.notificationRequired = notificationRequired;
	}

	public long getProcessID() {
		return this.processID;
	}

	public void setProcessID(long processID) {
		this.processID = processID;
	}

	public TaskNotification(java.lang.String taskName,
			java.lang.Boolean notificationRequired, long processID) {
		this.taskName = taskName;
		this.notificationRequired = notificationRequired;
		this.processID = processID;
	}

}