package com.axa_space.axa_fmf_closenotification;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TaskDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Document")
	private java.lang.Byte document;

	public TaskDetails() {
	}

	public java.lang.Byte getDocument() {
		return this.document;
	}

	public void setDocument(java.lang.Byte document) {
		this.document = document;
	}

	public TaskDetails(java.lang.Byte document) {
		this.document = document;
	}

}